/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FileTrans_CONSTANTS_H
#define FileTrans_CONSTANTS_H

#include "FileTrans_types.h"



class FileTransConstants {
 public:
  FileTransConstants();

};

extern const FileTransConstants g_FileTrans_constants;



#endif
