/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "FileTrans_constants.h"



const FileTransConstants g_FileTrans_constants;

FileTransConstants::FileTransConstants() {
}



