// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TransferFile.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class TransferFileHandler : virtual public TransferFileIf {
 public:
  TransferFileHandler() {
    // Your initialization goes here
  }

  bool UploadFile(const std::string& file_name, const std::string& file_data, const int64_t file_length) {
    // Your implementation goes here
    printf("UploadFile\n");
  }

  bool isExistFile(const std::string& file_name) {
    // Your implementation goes here
    printf("isExistFile\n");
  }

  void DownloadFile(std::string& _return, const std::string& file_name) {
    // Your implementation goes here
    printf("DownloadFile\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<TransferFileHandler> handler(new TransferFileHandler());
  ::std::shared_ptr<TProcessor> processor(new TransferFileProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

